[package]
name = "fe-env-mapper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
env-file-reader = "0"
walkdir = "2"
dotenvy = {workspace = true}
fs_extra = "1"
tokio = { workspace = true, features = ["fs", "rt-multi-thread", "macros"] }
async-trait = { workspace = true }
futures = "0.3.31"