[workspace]
members = [
    "examples/*",
    "crates/*",
]

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.90"
authors = []
license = "MIT/Apache-2.0"
homepage = ""
repository = ""
exclude = ["benches/", "tests/", "testdata/", "examples/*"]

[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.rust_2018_idioms = { level = "deny", priority = -1 }
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rustdoc.all = "warn"