name: Release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build_libs_and_docs:
    name: Build Libraries & Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build all crates
        run: cargo build --release --workspace

      - name: Generate documentation
        run: cargo doc --no-deps --workspace

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build_binaries:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Configure cross linker
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          mkdir -p .cargo
          sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
          echo '[target.aarch64-unknown-linux-gnu]' >> .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml

      - name: Build binary
        run: cargo build --bins --release --target ${{ matrix.target }}

      - name: Collect binary artifacts
        run: |
          mkdir -p artifacts
          for crate in $(cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select(.targets[] | .kind[] == "bin") | .name'); do
            BIN_PATH="target/${{ matrix.target }}/release/$crate"
            if [ -f "$BIN_PATH" ]; then
              cp "$BIN_PATH" "artifacts/${crate}-${{ matrix.target }}"
            fi
          done

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}


